require('packer_init')
require('core/autocmd')
require('core/colors')
require('core/keymaps')
require('core/options')
require('plugins/masonlsp')
require('plugins/null-ls')
require('plugins/nvim-cmp')
require('plugins/nvim-lspconfig')
require('plugins/prettier')
require('plugins/nvim-telescope')
require('plugins/which-key')
require('plugins/lualine')

require('plugins/nvim-tree')

--require('lualine')
--require('config')
--require('colors')
--require('plugin')
--require('mappings')
--require('completion')
--require('formatting')
--require('linting')
--require('lsp')
--require('masonlsp')

-- .vim source
vim.cmd('source ~/.config/nvim/plug-config/signify.vim')
